name: sb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi>=0.95.0
      - uvicorn>=0.21.1
      - pydantic>=1.10.7
      - pydantic-settings>=2.0.0
      - python-multipart>=0.0.6
      - email-validator>=2.0.0
      - python-jose>=3.3.0
      - passlib>=1.7.4
      - duckdb>=0.8.1
      - PyPDF2>=3.0.0
      - sentence-transformers>=2.2.2
      - faiss-cpu>=1.7.4
      - transformers>=4.30.0
      - python-dotenv>=1.0.0
